SACAAE/Models/Plaza.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace SACAAE.Models
{
    public class Plaza
    {
        public int ID { get; set; }
        public string Code { get; set; }
        public string PlazaType { get; set; }
        public string TimeType { get; set; }
        public int? TotalHours { get; set; }
        public int? EffectiveTime { get; set; }

        public virtual ICollection<PlazaXProfessor> PlazasXProfessors { get; set; }
    }
}

SACAAE/Models/ViewModels/PlazaViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SACAAE.Models.ViewModels
{
    public class PlazaCreateViewModel
    {
        public string Code { get; set; }
        public string PlazaType { get; set; }
        public SelectList PlazaTypeList { get; set; }
        public string TimeType { get; set; }
        public SelectList TimeTypeList { get; set; }
        public int TotalHours { get; set; }
        public int EffectiveTime { get; set; }
    }

    public class PlazaEditViewModel
    {
        public int ID { get; set; }
        public string Code { get; set; }
        public string PlazaType { get; set; }
        public SelectList PlazaTypeList { get; set; }
        public string TimeType { get; set; }
        public SelectList TimeTypeList { get; set; }
        public int TotalHours { get; set; }
        public int EffectiveTime { get; set; }
    }

    public class PlazaDetailViewModel
    {
        public int ID { get; set; }
        public string Code { get; set; }
        public string PlazaType { get; set; }
        public string TimeType { get; set; }
        public int TotalHours { get; set; }
        public int EffectiveTime { get; set; }
        public int TotalAllocate { get; set; }
        public List<PlazaAllocateProfessor> Professors { get; set; }
    }

    public class PlazaAllocateViewModel
    {
        public int ID { get; set; }
        public int TotalAllocate { get; set; }
        public List<PlazaAllocateProfessor> Professors { get; set; }
    }

    public class PlazaAllocateProfessor
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public int Allocate { get; set; }
    }

}

SACAAE/Controllers/PlazasController.cs
using Newtonsoft.Json;
using SACAAE.Data_Access;
using SACAAE.Models;
using SACAAE.Models.ViewModels;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;

namespace SACAAE.Controllers
{
    [Authorize]
    public class PlazasController : Controller
    {
        private SACAAEContext db = new SACAAEContext();                     // Database context
        private const string TempDataMessageKey = "MessageError";          
        private const string TempDataMessageKeySuccess = "MessageSuccess";

        /// GET: Plaza
        /// <author>Adonis Mora Angulo</author>
        /// <summary>
        /// All plazas from database
        /// </summary>
        /// <returns></returns>
        public ActionResult Index()
        {
            return View(db.Plazas.ToList());
        }

        /// GET: Plaza/Details/5
        /// <author>Adonis Mora Angulo</author>
        /// <summary>
        /// Details from a specific plaza and allocation of professors
        /// </summary>
        /// <param name="id">Plaza's id</param>
        /// <returns></returns>
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Plaza vPlaza = db.Plazas.Find(id);
            if (vPlaza == null)
            {
                return HttpNotFound();
            }
            var vPlazaProfessorList = vPlaza.PlazasXProfessors.OrderByDescending(p => p.PercentHours)
                                                              .ThenBy(p => p.Professor.Name).ToList();
            var vProfessors = new List<PlazaAllocateProfessor>();
            vPlazaProfessorList.ForEach(p => vProfessors.Add(new PlazaAllocateProfessor()
            {
                ID = p.ProfessorID,
                Name = p.Professor.Name,
                Allocate = p.PercentHours
            }));

            var viewModel = new PlazaDetailViewModel()
            {
                ID = vPlaza.ID,
                Code = vPlaza.Code,
                PlazaType = vPlaza.PlazaType,
                TimeType = vPlaza.TimeType,
                TotalHours = vPlaza.TotalHours.GetValueOrDefault(),
                EffectiveTime = vPlaza.EffectiveTime.GetValueOrDefault(),
                TotalAllocate = sumAllocate(vProfessors),
                Professors = vProfessors
            };

            return View(viewModel);
        }

        /// GET: Plaza/Create
        /// <author>Adonis Mora Angulo</author>
        /// <summary>
        /// Initialize the view to add new plazas
        /// </summary>
        /// <returns></returns>
        public ActionResult Create()
        {
            var viewModel = new PlazaCreateViewModel()
            {
                PlazaTypeList = new SelectList(new List<string>() { "Interna", "Externa" }),
                TimeTypeList = new SelectList(new List<string>() { "Completo", "Parcial" })
            };

            return View(viewModel);
        }

        /// POST: Plaza/Create
        /// <author>Adonis Mora Angulo</author>
        /// <summary>
        /// Add a new plaza to the system
        /// </summary>
        /// <param name="viewModel">Represents the information of a new plaza</param>
        /// <returns></returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(PlazaCreateViewModel viewModel)
        {
            if (ModelState.IsValid)
            {
                var vPlaza = new Plaza()
                {
                    Code = viewModel.Code,
                    PlazaType = viewModel.PlazaType,
                    TimeType = viewModel.TimeType,
                    TotalHours = viewModel.TotalHours,
                    EffectiveTime = viewModel.EffectiveTime
                };

                db.Plazas.Add(vPlaza);
                db.SaveChanges();

                TempData[TempDataMessageKeySuccess] = "Plaza creada exitosamente";
                return RedirectToAction("Index");
            }

            return View(viewModel);
        }

        /// GET: Plaza/Edit/5
        /// <author>Adonis Mora Angulo</author>
        /// <summary>
        /// Initialize the view to edit a plaza
        /// </summary>
        /// <param name="id">Plaza's id</param>
        /// <returns></returns>
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Plaza vPlaza = db.Plazas.Find(id);
            if (vPlaza == null)
            {
                return HttpNotFound();
            }
            var viewModel = new PlazaEditViewModel()
            {
                ID = vPlaza.ID,
                Code = vPlaza.Code,
                PlazaType = vPlaza.PlazaType,
                PlazaTypeList = new SelectList(new List<string>() { "Interna", "Externa" }),
                TimeType = vPlaza.TimeType,
                TimeTypeList = new SelectList(new List<string>() { "Completo", "Parcial" }),
                TotalHours = vPlaza.TotalHours.GetValueOrDefault(),
                EffectiveTime = vPlaza.EffectiveTime.GetValueOrDefault()
            };

            return View(viewModel);
        }

        /// POST: Plaza/Edit/5
        /// <author>Adonis Mora Angulo</author>
        /// <summary>
        /// Edit a plaza information
        /// </summary>
        /// <param name="viewModel">Represents the edited information of a plaza</param>
        /// <returns></returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(PlazaEditViewModel viewModel)
        {
            if (ModelState.IsValid)
            {
                var vPlaza = db.Plazas.Find(viewModel.ID);
                vPlaza.Code = viewModel.Code;
                vPlaza.PlazaType = viewModel.PlazaType;
                vPlaza.TimeType = viewModel.TimeType;
                vPlaza.TotalHours = viewModel.TotalHours;
                vPlaza.EffectiveTime = viewModel.EffectiveTime;

                db.Entry(vPlaza).State = EntityState.Modified;
                db.SaveChanges();

                TempData[TempDataMessageKeySuccess] = "Plaza editada exitosamente";
                return RedirectToAction("Index");
            }
            return View(viewModel);
        }

        /// POST: Plaza/Delete/5
        /// <author>Adonis Mora Angulo</author>
        /// <summary>
        /// Delete a plaza from the system
        /// </summary>
        /// <param name="id">Plaza's id</param>
        /// <returns></returns>
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Plaza vPlaza = db.Plazas.Find(id);
            db.Plazas.Remove(vPlaza);
            db.SaveChanges();

            TempData[TempDataMessageKeySuccess] = "Plaza eliminada exitosamente";
            return RedirectToAction("Index");
        }

        /// GET: Plaza/Allocate/5
        /// <author>Adonis Mora Angulo</author>
        /// <summary>
        /// Initialize the view to allocate professors to a plaza
        /// </summary>
        /// <param name="id">Plaza's id</param>
        /// <returns></returns>
        public ActionResult Allocate(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Plaza vPlaza = db.Plazas.Find(id);
            if (vPlaza == null)
            {
                return HttpNotFound();
            }
            var vPlazaProfesorList = vPlaza.PlazasXProfessors.OrderByDescending(p => p.PercentHours)
                                                             .ThenBy(p => p.Professor.Name).ToList();
            var vProfessors = new List<PlazaAllocateProfessor>();
            vPlazaProfesorList.ForEach(p => vProfessors.Add(new PlazaAllocateProfessor()
            {
                ID = p.ProfessorID,
                Name = p.Professor.Name,
                Allocate = p.PercentHours
            }));

            var viewModel = new PlazaAllocateViewModel()
            {
                ID = vPlaza.ID,
                TotalAllocate = sumAllocate(vProfessors),
                Professors = vProfessors
            };

            return View(viewModel);
        }

        /// POST: Plaza/Allocate/5
        /// <author>Adonis Mora Angulo</author>
        /// <summary>
        /// Allocate a professor to a plaza
        /// </summary>
        /// <param name="viewModel">Represents the new professor allocation on a plaza</param>
        /// <returns></returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Allocate(PlazaAllocateViewModel viewModel)
        {
            var vPlaza = db.Plazas.Find(viewModel.ID);
            var vNewProfe = viewModel.Professors.Last();
            vPlaza.PlazasXProfessors.Add(new PlazaXProfessor()
            {
                ProfessorID = vNewProfe.ID,
                PercentHours = vNewProfe.Allocate
            });
            db.SaveChanges();
            
            return RedirectToAction("Allocate", new { id = viewModel.ID });
        }

        /// POST: Plaza/EditAllocate/5
        /// <author>Adonis Mora Angulo</author>
        /// <summary>
        /// Edit the professor allocated on a plaza
        /// </summary>
        /// <param name="viewModel">Represents the edited professor allocated on a plaza</param>
        /// <returns></returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult EditAllocate(PlazaAllocateViewModel viewModel)
        {
            var vPlazaID = viewModel.ID;
            var vProfeID = viewModel.Professors[0].ID;

SACAAE/Views/Plazas/Allocate.cshtml
@model SACAAE.Models.ViewModels.PlazaAllocateViewModel

@{
    ViewBag.Title = "Asignación de Plazas";
    Layout = "~/Views/Shared/Privado.cshtml";
}
@section Scripts {
    <script src="@Url.Content("~/Scripts/SiteScripts/plazaAllocate.js")"></script>
}

<h2 class="page-header">Asignación de Plazas</h2>

<div class="col-md-10">
    @using (Html.BeginForm("Allocate", "Plazas", FormMethod.Post, new { id = "allocateForm" }))
    { 
    @Html.AntiForgeryToken()
    @Html.HiddenFor(model => model.ID)
    @Html.HiddenFor(model => model.TotalAllocate)
    <p class="col-md-12">
        <strong>Distribución de la Plaza</strong>
    </p>
    <div class="col-md-12">
        @{
        var ta = @Model.TotalAllocate;
        }
        <div class="col-md-9" style="padding-left:0px;">
            <div class="progress">
                <div class="progress-bar" role="progressbar" aria-valuenow="@ta" aria-valuemin="0" aria-valuemax="100" style="width: @ta%;">
                    <span class="sr-only">@ta% Asignado</span>
                </div>
            </div>
        </div>
        <p class="col-md-1">
            @ta%
        </p>
    </div>

    <p class="col-md-12">
        <strong>Profesores</strong>
    </p>
    <div class="col-md-12" id="profesores">
        @Html.Hidden("professorCount", Model.Professors.Count)
    @if (Model.Professors.Count == 0)
    {
        <div class="row text-center">
            <label>No existen profesores asignados</label>
        </div>
    }
    @for (var i = 0; i < Model.Professors.Count; i++)
    {
        @Html.HiddenFor(model => model.Professors[i].ID)
        @Html.HiddenFor(model => model.Professors[i].Name)
        @Html.HiddenFor(model => model.Professors[i].Allocate)
        var pa = @Model.Professors[i].Allocate;
        <p class="col-md-5" style="padding-left:0px">
            @Model.Professors[i].Name
        </p>
        <div class="col-md-4" style="padding-left:0px;">
            <div class="progress">
                <div class="progress-bar progress-bar-info" role="progressbar" aria-valuenow="@pa" aria-valuemin="0" aria-valuemax="100" style="width: @pa%;">
                    <span class="sr-only">@pa Asignado</span>
                </div>
            </div>
        </div>
        <p class="col-md-1">
            @pa%
        </p>
        <div class="col-md-2">
            <a href="" onclick="initEdit(@i)" data-toggle="modal" data-target="#editModal" title="Editar"><span class="glyphicon glyphicon-pencil" aria-hidden="true"></span></a> &nbsp
            <a href="" onclick="initDelete(@i)" data-toggle="modal" data-target="#deleteModal" title="Eliminar"><span class="glyphicon  glyphicon-trash" aria-hidden="true"></span></a>
        </div>
    }
    </div>

    <br />
    <input class="btn" value="Volver" type="button" onclick="location.href='@Url.Action("Index")';" />
    <a href="" onclick="initAdd()" data-toggle="modal" data-target="#addModal"><span class="glyphicon glyphicon-plus-sign" aria-hidden="true"></span>  Agregar Profesor</a>

    <!-- Modals -->
    <!-- Add professor -->
    <div class="modal fade" id="addModal" tabindex="-1" role="dialog" aria-labelledby="addModalLabel">
        <div class="modal-dialog" role="document">

            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title" id="myModalLabel">Agregar Profesor</h4>
                </div>
                <div class="modal-body">
                    <label>Profesor</label>
                    <select id="newProfe" class="form-control"></select>
                    <label>Porcentaje</label>
                    <input id="addPercent" class="form-control" type="number" min="0" placeholder="max @(100 - ta)%" oninput="addValidate();" />
                    <label>*Máximo @(100 - ta)%</label>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Cerrar</button>
                    <button type="submit" class="btn btn-primary" id="addBtn" onclick="addProfessor()" disabled>Guardar cambios</button>
                </div>
            </div>
        </div>
    </div>
    <!-- Edit professor -->
    <div class="modal fade" id="editModal" tabindex="-1" role="dialog" aria-labelledby="editModalLabel">
        <div class="modal-dialog" role="document">

            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title" id="myModalLabel">Editar Profesor</h4>
                </div>
                <div class="modal-body">
                    <label>Profesor</label>
                    <input id="editProfe" class="form-control" disabled />
                    <label>Porcentaje</label>
                    <input id="editPercent" class="form-control" type="number" min="0" oninput="editValidate();" />
                    <label id="editLabel"></label>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Cerrar</button>
                    <button type="button" class="btn btn-primary" id="editBtn" onclick="editProfessor()">Guardar cambios</button>
                </div>
            </div>
        </div>
    </div>
    <!-- Delete professor -->
    <div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel">
        <div class="modal-dialog" role="document">

            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title" id="myModalLabel">Eliminar Profesor</h4>
                </div>
                <div class="modal-body">
                    <h2>¿Esta seguro que desea eliminar al profesor de la plaza?</h2>
                    <label>Profesor</label>
                    <input id="deleteProfe" class="form-control" disabled />
                    <label>Porcentaje</label>
                    <input id="deletePercent" class="form-control" disabled />
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Cerrar</button>
                    <button type="button" class="btn btn-primary" id="deleteBtn" onclick="deleteProfessor()">Eliminar</button>
                </div>
            </div>
        </div>
    </div>
    }
</div>

SACAAE/Views/Plazas/Create.cshtml
@model SACAAE.Models.ViewModels.PlazaCreateViewModel

@{
    ViewBag.Title = "Agregar Plaza";
    Layout = "~/Views/Shared/Privado.cshtml";
}
@section Scripts {
    <script src="@Url.Content("~/Scripts/SiteScripts/plazaCreate.js")"></script>
}

<h2 class="page-header">Agregar Plaza</h2>

<div class="col-lg-4">
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    
    <div class="form-group">
        @Html.Label("Código", htmlAttributes: new { @class = "control-label" })
        @Html.EditorFor(model => model.Code, new { htmlAttributes = new { @class = "form-control", @placeholder = "Código de Plaza" } })
        @Html.ValidationMessageFor(model => model.Code, "", new { @class = "text-danger" })
    </div>

    <div class="form-group">
        @Html.Label("Tipo de Plaza", htmlAttributes: new { @class = "control-label" })
        @Html.DropDownListFor(model => model.PlazaType, Model.PlazaTypeList, new { @class = "form-control" } )
        @Html.ValidationMessageFor(model => model.PlazaType, "", new { @class = "text-danger" })
    </div>

    <div class="form-group">
        @Html.Label("Tipo según Tiempo", htmlAttributes: new { @class = "control-label" })
        @Html.DropDownListFor(model => model.TimeType, Model.TimeTypeList, new { @class = "form-control" })
        @Html.ValidationMessageFor(model => model.TimeType, "", new { @class = "text-danger" })
    </div>

    <div class="form-group">
       @Html.Label("Horas Totales", htmlAttributes: new { @class = "control-label" })
        @Html.EditorFor(model => model.TotalHours, new { htmlAttributes = new { @class = "form-control" } })
        @Html.ValidationMessageFor(model => model.TotalHours, "", new { @class = "text-danger" })
    </div>

    <div class="form-group">
        @Html.Label("Tiempo de Vigencia (Meses)", htmlAttributes: new { @class = "control-label" })
        @Html.EditorFor(model => model.EffectiveTime, new { htmlAttributes = new { @class = "form-control" } })
        @Html.ValidationMessageFor(model => model.EffectiveTime, "", new { @class = "text-danger" })
    </div>

    <div class="form-group">
        <input type="submit" value="Crear" class="btn" id="createBtn" /> |
        @Html.ActionLink("Regresar", "Index")
    </div>
}
</div>

SACAAE/Views/Plazas/Details.cshtml
@model SACAAE.Models.ViewModels.PlazaDetailViewModel

@{
    ViewBag.Title = "Detalles de la Plaza";
    Layout = "~/Views/Shared/Privado.cshtml";
}

<h2 class="page-header">Detalles de la Plaza</h2>

<div class="col-md-8">
    <p class="col-md-1">
        <strong>Código</strong>
    </p>
    <p class="col-md-11">
        @Html.DisplayFor(model => model.Code)
    </p>

    <p class="col-md-1">
        <strong>Tipo</strong>
    </p>
    <div class="col-md-2">
        <strong>Plaza</strong>
        <br />
        <span>@Html.DisplayFor(model => model.PlazaType)</span>
    </div>
    <div class="col-md-9">
        <strong>Tiempo</strong>
        <br />
        <span>@Html.DisplayFor(model => model.TimeType)</span>
    </div>

    <p class="col-md-1">
        <strong>Tiempo</strong>
    </p>
    <div class="col-md-2">
        <strong>Horas Totales</strong>
        <br />
        <span>@Html.DisplayFor(model => model.TotalHours)</span>
    </div>
    <div class="col-md-9">
        <strong>Vigencia</strong>
        <br />
        <span>@Html.DisplayFor(model => model.EffectiveTime) Meses</span>
    </div>

    <p class="col-md-12">
        <strong>Distribución de la Plaza</strong>
    </p>
    <div class="col-md-12">
        @{
            var ta = @Model.TotalAllocate;
        }
        <div class="col-md-11" style="padding-left:0px;">
            <div class="progress">
                <div class="progress-bar" role="progressbar" aria-valuenow="@ta" aria-valuemin="0" aria-valuemax="100" style="width: @ta%;">
                    <span class="sr-only">@ta% Asignado</span>
                </div>
            </div>
        </div>
        <p class="col-md-1">
            @ta%
        </p>
    </div>

    <p class="col-md-12">
        <strong>Profesores</strong>
    </p>
    <div class="col-md-12">
    @if(Model.Professors.Count == 0)
    {
        <div class="row text-center">
            <label>No existen profesores asignados</label>
        </div>
    }
    @for (var i = 0; i < Model.Professors.Count; i++)
    {
        var pa = @Model.Professors[i].Allocate;
        <p class="col-md-5" style="padding-left:0px">
            @Model.Professors[i].Name
        </p>
        <div class="col-md-6" style="padding-left:0px;">
            <div class="progress">
                <div class="progress-bar" role="progressbar" aria-valuenow="@pa" aria-valuemin="0" aria-valuemax="100" style="width: @pa%;">
                    <span class="sr-only">@pa Asignado</span>
                </div>
            </div>
        </div>
        <p class="col-md-1">
            @pa%
        </p>
    }
    </div>

    <br />
    <input class="btn" value="Editar" type="button" onclick="location.href='@Url.Action("Edit", new { id = Model.ID })';" />
    <input class="btn" value="Asignaciones" type="button" onclick="location.href='@Url.Action("Allocate", new { id = Model.ID })';" />
    <input class="btn" value="Volver" type="button" onclick="location.href='@Url.Action("Index")';" />
</div>

SACAAE/Views/Plazas/Edit.cshtml
@model SACAAE.Models.ViewModels.PlazaEditViewModel

@{
    ViewBag.Title = "Editar Plaza";
    Layout = "~/Views/Shared/Privado.cshtml";
}
@section Scripts {
    <script src="@Url.Content("~/Scripts/SiteScripts/plazaEdit.js")"></script>
}

<h2 class="page-header">Editar Plaza</h2>

<div class="col-lg-4">
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()
        @Html.HiddenFor(model => model.ID)
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            @Html.Label("Código", htmlAttributes: new { @class = "control-label" })
            @Html.EditorFor(model => model.Code, new { htmlAttributes = new { @class = "form-control", @placeholder = "Código de Plaza" } })
            @Html.ValidationMessageFor(model => model.Code, "", new { @class = "text-danger" })
        </div>

        <div class="form-group">
            @Html.Label("Tipo de Plaza", htmlAttributes: new { @class = "control-label" })
            @Html.DropDownListFor(model => model.PlazaType, Model.PlazaTypeList, new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.PlazaType, "", new { @class = "text-danger" })
        </div>

        <div class="form-group">
            @Html.Label("Tipo según Tiempo", htmlAttributes: new { @class = "control-label" })
            @Html.DropDownListFor(model => model.TimeType, Model.TimeTypeList, new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.TimeType, "", new { @class = "text-danger" })
        </div>

        <div class="form-group">
            @Html.Label("Horas Totales", htmlAttributes: new { @class = "control-label" })
            @Html.EditorFor(model => model.TotalHours, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.TotalHours, "", new { @class = "text-danger" })
        </div>

        <div class="form-group">
            @Html.Label("Tiempo de Vigencia (Meses)", htmlAttributes: new { @class = "control-label" })
            @Html.EditorFor(model => model.EffectiveTime, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.EffectiveTime, "", new { @class = "text-danger" })
        </div>

        <div class="form-group">
            <input type="submit" value="Guardar Cambios" class="btn" id="editBtn" /> |
            @Html.ActionLink("Regresar", "Index")
        </div>
    }
</div>