SACAAE/Models/Schedule.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace SACAAE.Models
{
    public class Schedule
    {
        public int ID { get; set; }
        public string Day { get; set; }
        public string StartHour { get; set; }
        public string EndHour { set; get; }

        public virtual ICollection<CommissionXProfessor> CommissionsXProfessors { get; set; }
        public virtual ICollection<ProjectXProfessor> ProjectsXProfessors { get; set; }
        public virtual ICollection<GroupClassroom> GroupsClassroom { get; set; }
    }
}

SACAAE/Models/ViewModels/ProfesorViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace SACAAE.Models.ViewModels
{
    public class ProfesorViewModel
    {
        public int ID { get; set; }
        public String Name { get; set; }
        public String Link { get; set; }
        public int StateID { get; set; }
        public String Tel1 { get; set; }
        public String Tel2 { get; set; }
        public String Email { get; set; }
        public double LoadAcademic { get; set; }
        public double TECHours { get; set; }
        public double ReconocimientoHours { get; set; }
        public double RecargoHours { get; set; }
        public double TotalHours { get; set; }
    }
}

SACAAE/Controllers/ProfesorController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using SACAAE.Models;
using SACAAE.Data_Access;
using SACAAE.Models.ViewModels;
using Newtonsoft.Json;
using SACAAE.WebService_Models;
using SACAAE.Helpers;


namespace SACAAE.Controllers
{
    public class ProfesorController : Controller
    {
        private SACAAEContext db = new SACAAEContext();
        private LoadAcademicHelper LAHelper = new LoadAcademicHelper();
        private const string TempDataMessageKeySuccess = "MessageSuccess";
        private const string TempDataMessageKeyError = "MessageError";
        SACAAE.Helpers.LoadAcademicHelper.ReporteInfo vReportInfo = new SACAAE.Helpers.LoadAcademicHelper.ReporteInfo();
        // GET: /Professor/
        public ActionResult Index()
        {
            var Professors = db.Professors.ToList();
            int vPeriod = int.Parse(Request.Cookies["Periodo"].Value);
            var viewModel = new List<ProfesorViewModel>();

            SACAAE.Helpers.LoadAcademicHelper.ReporteInfo vReportInfo = new SACAAE.Helpers.LoadAcademicHelper.ReporteInfo();
            vReportInfo = LAHelper.setCourses(vReportInfo, vPeriod);
            vReportInfo = LAHelper.setProjects(vReportInfo, vPeriod);
            vReportInfo = LAHelper.setCommissions(vReportInfo, vPeriod);

            SACAAE.Helpers.LoadAcademicHelper.Profesor[] array_profesores = 
                vReportInfo.todo_profesores.OrderBy(c => c.Profesor_Nombre).ToArray();
            
            string profe_actual = "";

            List<ProfesorViewModel> vProfList = new List<ProfesorViewModel>();
            foreach (SACAAE.Helpers.LoadAcademicHelper.Profesor profe in array_profesores)
            {
                double vCargaTEC = 0, vReconocimientoHours = 0, vRecargoHours = 0;

                if (profe_actual.Equals(""))
                {
                    profe_actual = profe.Profesor_Nombre;
                }

                if (!profe_actual.Equals(profe.Profesor_Nombre))
                {
                    if (vReportInfo.profesores_carga_tec.ContainsKey(profe_actual))                 
                        vCargaTEC = vReportInfo.profesores_carga_tec[profe_actual];

                    if (vReportInfo.profesores_carga_reconocimiento.ContainsKey(profe_actual))
                        vReconocimientoHours = vReportInfo.profesores_carga_reconocimiento[profe_actual];

                    if (vReportInfo.profesores_carga_recargo.ContainsKey(profe_actual))
                        vRecargoHours = vReportInfo.profesores_carga_recargo[profe_actual];

                    vProfList.Add(
                    new ProfesorViewModel()
                    {
                        ID = 0,
                        Name = profe_actual,
                        Link = "",
                        Tel1 = "",
                        Tel2 = "",
                        StateID = 1 ,
                        Email = "" ,
                        LoadAcademic = vCargaTEC * 100 / 40,
                        TECHours = vCargaTEC,
                        ReconocimientoHours = vReconocimientoHours,
                        RecargoHours = vRecargoHours,
                        TotalHours = vCargaTEC + vReconocimientoHours + vRecargoHours
                    });
                    profe_actual = profe.Profesor_Nombre;
                }
            }

            for (int vCont = 0; vCont < Professors.Count(); vCont++) 
            {
                Professor vProf = Professors.ElementAt(vCont);
                double vTecHours = 0, vReconocimientoHoursAux = 0, vRecargoHoursAux = 0, vAcademicLoad = 0;
                if ((vProfList.Find(item => item.Name == vProf.Name)) != null)
                {
                    vTecHours = vProfList.Find(item => item.Name == vProf.Name).TECHours;
                    vReconocimientoHoursAux = vProfList.Find(item => item.Name == vProf.Name).ReconocimientoHours;
                    vRecargoHoursAux = vProfList.Find(item => item.Name == vProf.Name).RecargoHours;
                    vAcademicLoad = vProfList.Find(item => item.Name == vProf.Name).LoadAcademic;
                }

                viewModel.Add(
                    new ProfesorViewModel()
                    {
                        ID = vProf.ID,
                        Name = vProf.Name,
                        Link = vProf.Link,
                        Tel1 = vProf.Tel1,
                        Tel2 = vProf.Tel2,
                        StateID = vProf.StateID.GetValueOrDefault(),
                        Email = vProf.Email,
                        LoadAcademic = vAcademicLoad,
                        TECHours = vTecHours,
                        ReconocimientoHours = vReconocimientoHoursAux,
                        RecargoHours = vRecargoHoursAux,
                        TotalHours = vReconocimientoHoursAux + vTecHours + vRecargoHoursAux
                    });
            } 
              
            return View(viewModel);
        }

        // GET: /Professor/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Professor profesor = db.Professors.Find(id);
            if (profesor == null)
            {
                return HttpNotFound();
            }
            return View(profesor);
        }

        // GET: /Professor/Create
        public ActionResult Create()
        {
            ViewBag.StateID = new SelectList(db.States, "ID", "Name");
            return View();
        }

        // POST: /Professor/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include="ID,Name,Link,StateID,Tel1,Tel2,Email")] Professor profesor)
        {
            if (ModelState.IsValid)
            {
                db.Professors.Add(profesor);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.StateID = new SelectList(db.States, "ID", "Name", profesor.StateID);
            return View(profesor);
        }

        // GET: /Professor/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Professor profesor = db.Professors.Find(id);
            if (profesor == null)
            {
                return HttpNotFound();
            }
            ViewBag.StateID = new SelectList(db.States, "ID", "Name", profesor.StateID);
            return View(profesor);
        }

        // POST: /Professor/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include="ID,Name,Link,StateID,Tel1,Tel2,Email")] Professor profesor)
        {
            if (ModelState.IsValid)
            {
                db.Entry(profesor).State = EntityState.Modified;
                TempData[TempDataMessageKeySuccess] = "Profesor editado correctamente";
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.StateID = new SelectList(db.States, "ID", "Name", profesor.StateID);
            return View(profesor);
        }

        // GET: /Professor/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Professor profesor = db.Professors.Find(id);
            if (profesor == null)
            {
                return HttpNotFound();
            }
            return View(profesor);
        }

        // POST: /Professor/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Professor profesor = db.Professors.Find(id);
            db.Professors.Remove(profesor);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        // GET: Professor/Schedule/5
        public ActionResult Schedule(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Professor profesor = db.Professors.Find(id);
            if (profesor == null)
            {
                return HttpNotFound();
            }

            var actualPeriod = int.Parse(Request.Cookies["Periodo"].Value);
            var data = new ScheduleDataList();
            var courses = db.SP_getAllCoursesPerProf(actualPeriod, profesor.Name).ToList();
            var commissions = db.SP_getAllCommissionsPerProf(actualPeriod, profesor.Name).ToList();
            var projects = db.SP_getAllProjectsPerProf(actualPeriod, profesor.Name).ToList();

            courses.ForEach(p => data.add(
                p.Day,
                (p.Name + "\nGrupo: " + p.Number),
                DateTime.Parse(p.StartHour),
                DateTime.Parse(p.EndHour),
                "Curso")
            );

            commissions.ForEach(p => data.add(
                p.Day,
                p.Name,
                DateTime.Parse(p.StartHour),
                DateTime.Parse(p.EndHour),

SACAAE/Views/Profesor/Create.cshtml
@model SACAAE.Models.Professor

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/Privado.cshtml";
}

<h2>Create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Profesor</h4>
        <hr />
        @Html.ValidationSummary(true)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name)
                @Html.ValidationMessageFor(model => model.Name)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Link, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Link)
                @Html.ValidationMessageFor(model => model.Link)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.StateID, "StateID", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("StateID", String.Empty)
                @Html.ValidationMessageFor(model => model.StateID)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Tel1, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Tel1)
                @Html.ValidationMessageFor(model => model.Tel1)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Tel2, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Tel2)
                @Html.ValidationMessageFor(model => model.Tel2)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email)
                @Html.ValidationMessageFor(model => model.Email)
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

SACAAE/Views/Profesor/Delete.cshtml
@model SACAAE.Models.Professor

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/Privado.cshtml";
}

<h2>Eliminar Profesor</h2>

<h3>Está seguro que desea eliminarlo?</h3>
<div>
    <dl class="dl-horizontal">
        <dt>
            Estado
        </dt>

        <dd>
            @Html.DisplayFor(model => model.State.Name)
        </dd>

        <dt>
            Nombre
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Link)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Link)
        </dd>

        <dt>
            Teléfono 1
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Tel1)
        </dd>

        <dt>
            Teléfono 2
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Tel2)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Atrás", "Index")
        </div>
    }
</div>

SACAAE/Views/Profesor/Details.cshtml
@model SACAAE.Models.Professor

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/Privado.cshtml";
}

<h2>Detalles de un Profesor</h2>

<div>
    <h4>Profesor</h4>
	<hr />
    <dl class="dl-horizontal">
        <dt>
            Estado
        </dt>

        <dd>
            @Html.DisplayFor(model => model.State.Name)
        </dd>

        <dt>
            Nombre
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Link)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Link)
        </dd>

        <dt>
            Teléfono 1
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Tel1)
        </dd>

        <dt>
            Teléfono 2
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Tel2)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Editar", "Edit", new { id = Model.ID }) |
    @Html.ActionLink("Atrás", "Index")
</p>

SACAAE/Views/Profesor/Edit.cshtml
@model SACAAE.Models.Professor

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/Privado.cshtml";
}

<h2>Editar Profesor</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Profesor</h4>
        <hr />
        @Html.ValidationSummary(true)
        @Html.HiddenFor(model => model.ID)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name)
                @Html.ValidationMessageFor(model => model.Name)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Link, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Link)
                @Html.ValidationMessageFor(model => model.Link)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.StateID, "StateID", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("StateID", String.Empty)
                @Html.ValidationMessageFor(model => model.StateID)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Tel1, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Tel1)
                @Html.ValidationMessageFor(model => model.Tel1)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Tel2, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Tel2)
                @Html.ValidationMessageFor(model => model.Tel2)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email)
                @Html.ValidationMessageFor(model => model.Email)
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Atrás", "Index")
</div>

SACAAE/Views/Profesor/Index.cshtml
@model IEnumerable<SACAAE.Models.ViewModels.ProfesorViewModel>

@{
    ViewBag.Title = "Profesores";
    Layout = "~/Views/Shared/Privado.cshtml";
}

@section scripts {
    <script type="text/javascript">
        $(document).ready(function () {
            $('#indexTable').DataTable({
                "language": {
                    url: "/Content/DataTables/Spanish.json",
                },
                responsive: true
            });
        });
    </script>
}
<h1 class="page-header">
    Profesores
</h1>

@if (TempData.ContainsKey("MessageError"))
{
    <div class="alert alert-danger alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        @TempData["MessageError"].ToString()
    </div>
}
@if (TempData.ContainsKey("MessageSuccess"))
{
    <div class="alert alert-success alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        @TempData["MessageSuccess"].ToString()
    </div>
}

<p>
    <a href="@Url.Action("Create", "Profesor")"><span class="glyphicon glyphicon-plus-sign" aria-hidden="true"></span>  Agregar Profesor</a>
</p>

<div class="dataTables_wrapper">
    <table class="table table-hover" id="indexTable">
        <thead>
            <tr>
                <th class="text-center"> Nombre </th>
                <th class="text-center"> Carga </th>
                <th class="text-center"> Carga TEC </th>
                <th class="text-center"> Horas Recargo </th>
                <th class="text-center"> Horas Reconocimiento </th>
                <th class="text-center"> Total Horas </th>
                <th class="text-center"> Asignar a </th>
                <th class="text-center"> Acciones </th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Name)
                    </td>
                    <td class="text-center">@Html.DisplayFor(modelItem => item.LoadAcademic)% </td>
                    <td class="text-center">@Html.DisplayFor(modelItem => item.TECHours) </td>
                    <td class="text-center">@Html.DisplayFor(modelItem => item.RecargoHours) </td>
                    <td class="text-center">@Html.DisplayFor(modelItem => item.ReconocimientoHours) </td>
                    <td class="text-center">@Html.DisplayFor(modelItem => item.TotalHours) </td>

                    <td class="text-center">
                        @Html.ActionLink("Comisión", "Asignar", "ComisionProfesor", new { Profesor = item.ID},null) |
                        @Html.ActionLink("Proyecto", "Asignar", "ProyectoProfesor", new { Profesor = item.ID }, null) |
                        @Html.ActionLink("Curso", "Asignar", "CursoProfesor", new { Profesor = item.ID }, null)
                    </td>
                    <td class="text-center">
                        <a href="@Url.Action("Details", new { id = item.ID })" title="Ver detalle"><span class="glyphicon glyphicon-eye-open" aria-hidden="true"></span></a> &nbsp
                        <a href="@Url.Action("Edit", new { id = item.ID })" title="Editar"><span class="glyphicon glyphicon-pencil" aria-hidden="true"></span></a> &nbsp
                        <a href="@Url.Action("Delete", new { id = item.ID })" title="Eliminar"><span class="glyphicon  glyphicon-trash" aria-hidden="true"></span></a>&nbsp
                        <a href="@Url.Action("Schedule", new { id = item.ID })" title="Ver Horario"><span class="glyphicon  glyphicon-time" aria-hidden="true"></span></a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>

SACAAE/Views/Profesor/Schedule.cshtml
@using SACAAE.Models.ViewModels
@model ScheduleProfessorViewModel
@{
    ViewBag.Title = "Horario Profesor";
    Layout = "~/Views/Shared/Privado.cshtml";
}
<div class="col-lg-12">

    <h2> Horario de Profesor </h2>
    <h4>
        <span class="label label-info">
            @Html.DisplayName("Profesor: ")
            @Html.DisplayFor(model => model.Name)
        </span>
    </h4>
    <table id="div_tabla" class="table table-condensed table-bordered">
        <thead>
            <tr>
                <th class="text-center">Horario</th>
                <th class="text-center">Lunes</th>
                <th class="text-center">Martes</th>
                <th class="text-center">Miércoles</th>
                <th class="text-center">Jueves</th>
                <th class="text-center">Viernes</th>
                <th class="text-center">Sábado</th>
            </tr>
        </thead>
        <tbody>
            @{
                var ommitList = new int[] { 0, 0, 0, 0, 0, 0 };
                var data = Model.ScheduleData;
                var start = DateTime.Parse("07:30 am");
                var end = start.AddMinutes(50);

                for(int i=0; i<15; i++)
                {
                    <tr>
                        <td>@getTime(start, end)</td>
                        @for (int j = 0; j < data.Count; j++)
                        {
                            if (ommitList[j] > 0)
                            {
                                ommitList[j]--;
                                continue;
                            }

                            var cellData = findData(data[j], i);
                            if (cellData == null)
                            {
                                <td></td>
                            }
                            else
                            {
                                if (cellData.Type == "Curso")
                                {
                                    <td class="table-course" rowspan="@cellData.Difference">@Html.Raw(Html.Encode(cellData.Name).Replace("\n", "<br />"))</td>
                                }
                                else if (cellData.Type == "Comisión")
                                {
                                    <td class="table-commission" rowspan="@cellData.Difference">@cellData.Name</td>
                                }
                                else 
                                {
                                    <td class="table-project" rowspan="@cellData.Difference">@cellData.Name</td>
                                }
                                ommitList[j] = cellData.Difference - 1;
                            }
                        }
                    </tr>
                    start = (start == DateTime.Parse("12:30 pm")) ? DateTime.Parse("1:00 pm") : start.AddHours(1);
                    end = (start == DateTime.Parse("12:30 pm")) ? start.AddMinutes(20) : start.AddMinutes(50);
                }
            }
        </tbody>
    </table>

    |  @Html.ActionLink("Regresar", "Index")  |

</div>

@section Scripts {
    <script src="@Url.Content("~/Scripts/date.js")"></script>
}
@functions{
    public string getTime(DateTime start, DateTime end)
    {
        return start.ToShortTimeString() + " a " + end.ToShortTimeString();
    }

    public ScheduleData findData(List<ScheduleData> list, int block)
    {
        for(int i=0; i<list.Count; i++)
        {
            if (list[i].StartBlock == block)
                return list[i];
        }
        return null;
    }
}