SACAAE/Controllers/ComisionController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using SACAAE.Models;
using SACAAE.Data_Access;
using SACAAE.Models.ViewModels;
using Newtonsoft.Json;
using System.Globalization;
using SACAAE.Helpers;

namespace SACAAE.Controllers
{
    public class ComisionController : Controller
    {
        private SACAAEContext db = new SACAAEContext();
        private ScheduleHelper dbHelper = new ScheduleHelper();
        private const string TempDataMessageKeySuccess = "MessageSuccess";
        private const string TempDataMessageKeyError = "MessageError";
        // GET: /Comision/
        public ActionResult Index()
        {
            String entidad = Request.Cookies["Entidad"].Value;
            if (entidad.Equals("TEC"))
            {
                var model = ObtenerComisionesXEntidad(1);
                return View(model);
            }
            else if (entidad.Equals("CIE"))
            {
                var model = ObtenerComisionesXEntidad(7);
                return View(model);
            }
            else if (entidad.Equals("TAE"))
            {
                var model = ObtenerComisionesXEntidad(5);
                return View(model);
            }
            else if (entidad.Equals("MAE"))
            {
                var model = ObtenerComisionesXEntidad(6);
                return View(model);
            }
            else if (entidad.Equals("DDE"))
            {
                var model = ObtenerComisionesXEntidad(11);
                return View(model);
            }
            else if (entidad.Equals("Emprendedores"))
            {
                var model = ObtenerComisionesXEntidad(12);
                return View(model);
            }
            else if (entidad.Equals("Actualizacion_Cartago"))
            {
                var model = ObtenerComisionesXEntidad(9);
                return View(model);
            }
            else
            {
                var model = ObtenerComisionesXEntidad(8); //Actualización San Carlos
                return View(model);
            }
        }

        // GET: /Comision/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Commission commission = db.Commissions.Find(id);
            //****************
            if (commission == null)
            {
                return HttpNotFound();
            }

            ProfessorAssignViewModel commissionViewModel = new ProfessorAssignViewModel();
            commissionViewModel.ID = commission.ID;
            commissionViewModel.Name = commission.Name;

            var vStartHour = commission.Start.ToString("dd/MM/yyyy");
            commissionViewModel.Start = vStartHour;

            var vEndHour = commission.End.ToString("dd/MM/yyyy");

            commissionViewModel.End = vEndHour;
            
            return View(commissionViewModel);
        }

        // GET: /Comision/Create
        public ActionResult Create()
        {
            ViewBag.EntityTypeID = new SelectList(db.EntityTypes, "ID", "Name");
            ViewBag.StateID = new SelectList(db.States, "ID", "Name");
            return View();
        }

        // POST: /Comision/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include="ID,Name,Start,End,StateID,EntityTypeID")] Commission commission)
        {
            String entidad = Request.Cookies["Entidad"].Value;
            int entidadID;

            if (entidad.Equals("TEC")) { entidadID = 1; }
            else if (entidad.Equals("CIE")) { entidadID = 7; }
            else if (entidad.Equals("TAE")) { entidadID = 5; }
            else if (entidad.Equals("MAE")) { entidadID = 6; }
            else if (entidad.Equals("DDE")) { entidadID = 11; }
            else if (entidad.Equals("Emprendedores")) { entidadID = 12; }
            else if (entidad.Equals("Actualizacion_Cartago")) { entidadID = 9; }
            else { entidadID = 8; }

            if (string.IsNullOrEmpty(commission.Name.Trim()))
                throw new ArgumentException("El nombre de la comisión no es válida. Por favor, inténtelo de nuevo");


            if (ModelState.IsValid)
            {
                commission.EntityTypeID = entidadID;
                commission.StateID = 1;
                db.Commissions.Add(commission);
                db.SaveChanges();
                TempData[TempDataMessageKeySuccess] = "Comisión creada correctamente.";
                return RedirectToAction("Index");
            }

            ViewBag.EntityTypeID = new SelectList(db.EntityTypes, "ID", "Name", commission.EntityTypeID);
            ViewBag.StateID = new SelectList(db.States, "ID", "Name", commission.StateID);
            return View(commission);
        }

        // GET: /Comision/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Commission commission = db.Commissions.Find(id);
            if (commission == null)
            {
                return HttpNotFound();
            }
            ViewBag.EntityTypeID = new SelectList(db.EntityTypes, "ID", "Name", commission.EntityTypeID);
            ViewBag.StateID = new SelectList(db.States, "ID", "Name", commission.StateID);
            return View(commission);
        }

        // POST: /Comision/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include="ID,Name,Start,End,StateID,EntityTypeID")] Commission commission)
        {

            if (!ExisteComision(commission))
            {
                AgregarComision(commission);
            }

            if (ModelState.IsValid)
            {
                var temp = db.Commissions.Find(commission.ID);

                if (temp != null)
                {
                    db.Entry(temp).Property(c => c.Name).CurrentValue = commission.Name;
                    db.Entry(temp).Property(c => c.Start).CurrentValue = commission.Start;
                    db.Entry(temp).Property(c => c.End).CurrentValue = commission.End;
                }
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(commission);
        }

        // GET: /Comision/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Commission commission = db.Commissions.Find(id);
            if (commission == null)
            {
                return HttpNotFound();
            }
            return View(commission);
        }

        //GET: /Comision/AsignarProfesorComision/5
        public ActionResult AsignarProfesorComision(int? id)
        
        {
            if (Request.UrlReferrer != null)
            {
                ViewBag.returnUrl = Request.UrlReferrer.ToString();
            }
            else
            {
                ViewBag.returnUrl = null;
            }

            Commission commission = db.Commissions.Find(id);
            ScheduleComissionViewModel commissionViewModel = new ScheduleComissionViewModel();
            commissionViewModel.Commissions = commission.Name;

            ViewBag.Professors = new SelectList(db.Professors.OrderBy(p => p.Name), "ID", "Name"); ;
            ViewBag.CommissionID = commission.ID.ToString();
            return View(commissionViewModel);
        }

        // POST: ComisionProfesor/AsignarProfesorComision
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult AsignarProfesorComision(ScheduleComissionViewModel pSchedule)
        {
            var vPeriod = Request.Cookies["Periodo"].Value;
            var vPeriodID = db.Periods.Find(int.Parse(vPeriod)).ID;

            var vHourCharge = Convert.ToInt32(pSchedule.HourCharge);
            var vCommissionID = Convert.ToInt32(pSchedule.Commissions);
            var vProfessorID = Convert.ToInt32(pSchedule.Professors);

            List<ScheduleComission> vSchedules = pSchedule.ScheduleCommission;
            string validate = dbHelper.validationsCommission(vCommissionID,vProfessorID,vPeriodID,vSchedules);
            if(validate.Equals("true"))
            {
                int totalHourAssign = 0;

                //Save Commission Professor
                CommissionXProfessor vCommissionProfessor = new CommissionXProfessor();
                vCommissionProfessor.CommissionID = Convert.ToInt32(vCommissionID);
                vCommissionProfessor.ProfessorID = Convert.ToInt32(vProfessorID);
                if (vHourCharge.Equals("1"))
                {
                    vCommissionProfessor.HourAllocatedTypeID = Convert.ToInt32(vHourCharge);
                }
                vCommissionProfessor.PeriodID = vPeriodID;
                vCommissionProfessor.Schedule = new List<Schedule>();

                //Calculate the total hour assign
                foreach (ScheduleComission vSchedule in vSchedules)
                {
                    Schedule vTempSchedule = existSchedule(vSchedule.Day, vSchedule.StartHour, vSchedule.EndHour);
                    if (vTempSchedule != null)
                    {
                        //Get id schedule

SACAAE/Views/Comision/AsignarProfesorComision.cshtml
@model SACAAE.Models.ViewModels.ScheduleComissionViewModel

@{
    ViewBag.Title = "Asignar";
    Layout = "~/Views/Shared/Privado.cshtml";
}

<link href="~/Content/custom.css" rel="stylesheet" />
@section Scripts {
    
    <script src="@Url.Content("~/Scripts/SiteScripts/GuardarDias.js")"></script>
    <script src="@Url.Content("~/Scripts/SiteScripts/assignProfesorCommission.js")"></script>


}

<body onload="Load()">
    <h2 class="page-header">Asignar Profesor a Comisión</h2>
    <div class="col-lg-4">
        <div class="span12">
            @if (TempData.ContainsKey("MessageError"))
            {
                <div class="alert alert-danger alert-dismissible" role="alert">
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    @TempData["MessageError"].ToString()
                </div>
            }
            @if (TempData.ContainsKey("MessageSuccess"))
            {
                <div class="alert alert-success alert-dismissible" role="alert">
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    @TempData["MessageSuccess"].ToString()
                </div>
            }
            @using (Html.BeginForm("AsignarProfesorComision", "Comision", FormMethod.Post, new { @id = "formPost" }))
            {
                @Html.AntiForgeryToken()
                @Html.ValidationSummary(true)

                

                <div class="editor-label">
                    @Html.Label("Comision")
                    <br />
                    @Html.DisplayFor(model => model.Commissions)
                </div>
                <br />
                <div class="editor-label">
                    @Html.Label("Profesores")
                </div>
                <div class="editor-field">
               
                         @Html.DropDownList("Professors", null, htmlAttributes: new { @class = "form-control" })
                </div>
              
                
                <div class="editor-field" style="display:inline">
                    
                </div>
                <br />
                <div>
                    @Html.Label("Hora Reconocimiento")
                </div>
                <div class="editor-field">
                    <select id="HourCharge" name="HourCharge" class="form-control">

                        <option selected="selected" value="1">Si</option>
                        <option value="0">No</option>
                    </select>
                </div>
                <br />

                <table id="schedule_commission">

                    <thead>
                        <tr>
                            <th>Dia</th>
                            <th>Inicio</th>
                            <th>Fin</th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr id="trRow1" data-day="Lunes" data-starthour="07:30 am" data-endhour="08:20 am">
                            <td>
                                <select id="tdRow1Day" onchange="onchangeDaySelection(1)">
                                    <option>Lunes</option>
                                    <option>Martes</option>
                                    <option>Miércoles</option>
                                    <option>Jueves</option>
                                    <option>Viernes</option>
                                    <option>Sábado</option>
                                </select>

                            </td>
                            <td>
                                <div id="campo_inicio">

                                    <select id="tdRow1StartHour" onchange="onchangeStartHourSelection(1)">
                                        <option>07:30 am</option>
                                        <option>08:30 am</option>
                                        <option>09:30 am</option>
                                        <option>10:30 am</option>
                                        <option>11:30 am</option>
                                        <option>12:30 pm</option>
                                        <option>01:00 pm</option>
                                        <option>02:00 pm</option>
                                        <option>03:00 pm</option>
                                        <option>04:00 pm</option>
                                        <option>05:00 pm</option>
                                        <option>06:00 pm</option>
                                        <option>07:00 pm</option>
                                        <option>08:00 pm</option>
                                        <option>09:00 pm</option>
                                    </select>

                                </div>
                            </td>
                            <td>
                                <select id="tdRow1EndHour" onchange="onchangeEndHourSelection(1)">
                                    <option>08:20 am</option>
                                    <option>09:20 am</option>
                                    <option>10:20 am</option>
                                    <option>11:20 am</option>
                                    <option>12:20 pm</option>
                                    <option>01:50 pm</option>
                                    <option>02:50 pm</option>
                                    <option>03:50 pm</option>
                                    <option>04:50 pm</option>
                                    <option>05:50 pm</option>
                                    <option>06:50 pm</option>
                                    <option>07:50 pm</option>
                                    <option>08:50 pm</option>
                                    <option>09:50 pm</option>
                                </select>
                            </td>
                            <td>
                                <a onclick="delete_row(1)" title="Eliminar"><span class="glyphicon glyphicon-remove" aria-hidden="true"></span></a>
                            </td>
                        </tr>
                    </tbody>
                </table>

                <!--<input id="Commissions" value="" class="form-control" hidden="hidden" />-->
                @Html.HiddenFor(m => m.Commissions)
                <p>
                    <a id="assign_comission" onclick="obtener_dias()"> <span class="glyphicon glyphicon-plus-sign" aria-hidden="true"></span> Agregar Horario</a>
                </p>

                <p>
                    <input id="buttonPost" type="button" value="Asignar" class="btn" onclick="submit_form()" />
                    <input type="button" value="Cancelar" class="btn" id="Cancelar" onclick="my_back(@ViewBag.CommissionID)" />
                </p>
            }
        </div>
    </div>
</body>

SACAAE/Views/Comision/Create.cshtml
@model SACAAE.Models.Commission

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/Privado.cshtml";
}

<div class="col-lg-4">
    <h2>Crear Comisi&oacute;n</h2>
    <hr />

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()
         @Html.ValidationSummary(true)
        
       <div class="editor-label">
            @Html.Label("Nombre")
        </div>
        <div class="editor-field">
            @Html.TextBoxFor(model => model.Name, new
               {
                   @class = "form-control",
                   @placeholder = "Nombre de la Comisión",
                   @required = "true"
               })
            @Html.ValidationMessageFor(model => model.Name)
        </div>
        
         <div class="editor-label">
            @Html.Label("Inicio")
        </div>
        <div class="editor-field">
            @Html.TextBoxFor(model => model.Start, new
               {
                   type = "date", @class = "form-control" 
               })
            @Html.ValidationMessageFor(model => model.Start)
        </div>
        
         <div class="editor-label">
            @Html.Label("Fin")
        </div>
        <div class="editor-field">
            @Html.TextBoxFor(model => model.End, new
               {
                   type = "date", @class = "form-control" 
               })
            @Html.ValidationMessageFor(model => model.End)
        </div>
        <br />
        
        <p>
            <input type="submit" value="Crear" class="btn" /> |  @Html.ActionLink("Regresar", "Index")
        </p>
    }

</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

SACAAE/Views/Comision/Delete.cshtml
@model SACAAE.Models.Commission

@{
    ViewBag.Title = "Eliminar";
    Layout = "~/Views/Shared/Privado.cshtml";
}
<div class="col-lg-4">
    <h2>Eliminar Comisi&oacute;n</h2>
    <hr />
    <div class="span12">
        <h4><span class="label label-warning">¿Est&aacute; seguro de que desea eliminar la informaci&oacute;n de esa Comisi&oacute;n?</span></h4>
        <br />
        <h4>
            <span class="label label-info">
                @Html.Label("Nombre")
                @Html.DisplayFor(model => model.Name)
            </span>
        </h4>
        <h4>
            <span class="label label-info">
                @Html.Label("Inicio")
                @Html.DisplayFor(model => model.Start)
            </span>
        </h4>
        <h4>
            <span class="label label-info">
                @Html.Label("Fin")
                @Html.DisplayFor(model => model.End)
            </span>
        </h4>
        <br />
        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()
            <p>
                <input type="submit" value="Eliminar" class="btn" />
                |
                @Html.ActionLink("Regresar", "Index")
            </p>
        }
    </div>
</div>

SACAAE/Views/Comision/Details.cshtml
@model SACAAE.Models.ViewModels.ProfessorAssignViewModel

@{
    ViewBag.Title = "Detalle";
    Layout = "~/Views/Shared/Privado.cshtml";
}
<link href="~/Content/custom.css" rel="stylesheet" />
<script src="@Url.Content("~/Scripts/SiteScripts/commissionDetails.js")"></script>

<br />
<h2>Detalles de la Comisi&oacute;n</h2>
<hr />
<!--Show success message-->
@if (TempData.ContainsKey("MessageError"))
{
    <div class="alert alert-danger alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        @TempData["MessageError"].ToString()
    </div>
}
@if (TempData.ContainsKey("MessageSuccess"))
{
    <div class="alert alert-success alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        @TempData["MessageSuccess"].ToString()
    </div>
}
<table id="commission_information">
    <thead>
    </thead>
    <tbody>
        <tr>
            <td class="static_info">Nombre</td>
            <td class="dynamic_info">@Html.DisplayFor(model => model.Name)</td>
        </tr>
        <tr>
            <td class="static_info">Inicio</td>
            <td class="dynamic_info">@Html.DisplayFor(model => model.Start)</td>
        </tr>
        <tr>
            <td class="static_info">Fin</td>
            <td class="dynamic_info">@Html.DisplayFor(model => model.End)</td>
        </tr>
    </tbody>

</table>
<h3>Profesores</h3>
<a href="@Url.Action("AsignarProfesorComision", new { id = Model.ID })">
    <span class="glyphicon glyphicon-plus-sign" aria-hidden="true"></span> Asignar Profesor
</a>
    
<table id="professor_assign_commission" class="table">
    <thead>
        <th>Nombre</th>
        <th>Horas Dedicadas</th>
        <th>Acciones</th>
    </thead>
               
    <tbody>
    </tbody>
</table>
   
<p>
    @Html.ActionLink("Editar", "Edit", new { id = Model.ID }) |
    @Html.ActionLink("Regresar", "Index")
</p>
   
 <!-- Delete professor -->
<div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel">
    <div class="modal-dialog" role="document">

        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="myModalLabel">Remover Profesor</h4>
            </div>
            <div class="modal-body">
                <h2>¿Esta seguro que desea remover al profesor de la comision?</h2>

            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Cerrar</button>
                <button type="button" class="btn btn-primary" id="deleteBtn" onclick="eliminar_asignacion_commission()">Eliminar</button>
            </div>
        </div>
    </div>
</div>

SACAAE/Views/Comision/Edit.cshtml
@model SACAAE.Models.Commission

@{
    ViewBag.Title = "Editar";
    Layout = "~/Views/Shared/Privado.cshtml";
}

<div class="col-lg-4">
    <h2>Editar Comisi&oacute;n</h2>
    <hr />
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()
        @Html.ValidationSummary(true)


        @Html.HiddenFor(model => model.ID)

        <div class="editor-label">
            @Html.Label("Nombre")
        </div>
        <div class="editor-field">
            @Html.TextBoxFor(model => model.Name, new
               {
                   @class = "form-control",
                   @required = "true"
               })
            @Html.ValidationMessageFor(model => model.Name)
        </div>

        <div class="editor-label">
            @Html.Label("Inicio")
        </div>
        <div class="editor-field">
            @Html.TextBoxFor(model => model.Start, new
               {
                   @class = "form-control",
                   @required = "true"
               })
            @Html.ValidationMessageFor(model => model.Start)
        </div>

        <div class="editor-label">
            @Html.Label("Fin")
        </div>
        <div class="editor-field">
            @Html.TextBoxFor(model => model.End, new
               {
                   @class = "form-control",
                   @required = "true"
               })
            @Html.ValidationMessageFor(model => model.End)
        </div>
        <br />
        <p>
            <input type="submit" value="Guardar" class="btn" />
            | @Html.ActionLink("Regresar", "Index")
        </p>
    }
    <div>
    </div>
</div>
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

SACAAE/Views/Comision/EditarAsignacion.cshtml
@model SACAAE.Models.ViewModels.ScheduleComissionViewModel

@{
    ViewBag.Title = "EditarAsignacion";
    Layout = "~/Views/Shared/Privado.cshtml";
}
<link href="~/Content/custom.css" rel="stylesheet" />
<script src="~/Scripts/jquery-2.1.4.js"></script>
<script src="@Url.Content("~/Scripts/SiteScripts/commissionEditAssign.js")"></script>

<br />
<h2>Editar Asignacion</h2>
<hr />
@if (TempData.ContainsKey("MessageError"))
{
    <div class="alert alert-danger alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        @TempData["MessageError"].ToString()
    </div>
}
@if (TempData.ContainsKey("MessageSuccess"))
{
    <div class="alert alert-success alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        @TempData["MessageSuccess"].ToString()
    </div>
}
@using (Html.BeginForm("EditarAsignacion", "Comision", FormMethod.Post, new { @id = "formPost" }))
{
    @Html.AntiForgeryToken()
    
    <br/>

<div class="row">
    <div class="col-sm-2"></div>
    <div class="col-lg-4">
        <div>
            <div class="editor-label">
                @Html.Label("Comision")
                <br />
                @Html.DisplayFor(model => model.Commissions)
            </div>
            <br />
            <div class="editor-label">
                @Html.Label("Profesor")
                <br />
                <div class="editor-field">
                    @Html.DropDownList("Professors", null, htmlAttributes: new { @class = "form-control" })
                </div>

            </div>
            <br />
            <div class="editor-field">
                @Html.Label("Tipo de Hora")

                <select id="HourCharge" name="HourCharge" class="form-control ">
                    <option value="1"> Reconocimiento </option>
                    <option value="2">Recargo</option>
                    <option selected="selected" value="3"> Carga </option>
                </select>
            </div>
            <br />
            <div class="editor-label">
                @Html.Label("Horario de Asignacion")
                <table id="assign_comission_schedule">
                    <thead>
                        <tr>
                            <th>Dia</th>
                            <th>Inicio</th>
                            <th>Fin</th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody></tbody>
                </table>

                <p>
                    <a id="assign_comission" onclick="obtener_dias()"> <span class="glyphicon glyphicon-plus-sign" aria-hidden="true"></span> Agregar Horario</a>
                </p>
            </div>
        </div>
        </div>
    <div class="col-sm-2"></div>
    
    </div>
    @Html.HiddenFor(m => m.Commissions)
    <p>
        <input type="button" value="Editar" class="btn" id="Editar_Asignacion" onclick="submit_form()"/> 
        <input type="button" value="Cancelar" class="btn" id="Cancelar" onclick="my_back(@ViewBag.CommissionID)"/>
    </p>
}

SACAAE/Views/Comision/Index.cshtml
@model IEnumerable<SACAAE.Models.Commission>

@section scripts {
    <script type="text/javascript">
        $(document).ready(function () {
            $('#indexTable').DataTable({
                "language": {
                    url: "/Content/DataTables/Spanish.json",
                },
                responsive: true
            });
        });
    </script>
}

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/Privado.cshtml";
}

<h1 class="page-header">
    Comisiones
</h1>

@if (TempData.ContainsKey("MessageError"))
{
    <div class="alert alert-danger alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        @TempData["MessageError"].ToString()
    </div>
}
@if (TempData.ContainsKey("MessageSuccess"))
{
    <div class="alert alert-success alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        @TempData["MessageSuccess"].ToString()
    </div>
}  
    
<p>
    <a href="@Url.Action("Create", "Comision")"><span class="glyphicon glyphicon-plus-sign" aria-hidden="true"></span>  Agregar Comisión</a>
</p>

<table class="table table-hover" id="indexTable">
    <thead>

        <tr>
            <th>
                @Html.Label("Nombre")
            </th>
            <th class="text-center">
                @Html.Label("Inicio")
            </th>
            <th class="text-center">
                @Html.Label("Fin")
            </th>
            <th class="text-center">
                @Html.Label("Estado")
            </th>
            <th class="text-center">Acciones</th>
        </tr>
    </thead>

    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td class="text-center">
                    @item.Start.ToString("dd/MM/yyyy")
                </td>
                <td class="text-center">
                    @item.End.ToString("dd/MM/yyyy")
                </td>
                <td class="text-center">
                    @Html.DisplayFor(modelItem => item.State.Name)
                </td>
                <td class="text-center">
                    <a href="@Url.Action("Details", new { id = item.ID })" title="Ver detalle"><span class="glyphicon glyphicon-eye-open" aria-hidden="true"></span></a>
                    <a href="@Url.Action("Edit", new { id = item.ID })" title="Editar"><span class="glyphicon glyphicon-pencil" aria-hidden="true"></span></a>
                    <a href="@Url.Action("Delete", new { id = item.ID })" title="Eliminar"><span class="glyphicon glyphicon-trash" aria-hidden="true"></span></a>


                </td>
            </tr>
        }
    </tbody>

</table>